development:
  adapter: mysql2
  database: ottos_appliance_development
  username: root
  password:
  host: localhost
  encoding: utf8

staging:
  adapter: mysql2
  database: ottos_appliance_staging
  username: root
  password:
  host: localhost
  encoding: utf8

test:
  adapter: mysql2
  database: ottos_appliance_test
  username: root
  password:
  host: localhost
  encoding: utf8
