
development:
  adapter: mysql2
  database: ottos_appliance_development
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  adapter: postgresql
  database: d5beb45brdlps1
  username: ozmskqnscuzvwq
  password: _ueaMZ7KAbqAwLitbCTnSbfq6H
  host: ec2-54-225-156-230.compute-1.amazonaws.com
  encoding: utf8

test:
  adapter: mysql2
  database: ottos_appliance_test
  username: root
  password:
  host: localhost
  encoding: utf8
