# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a86bf5214b1480671bbda4a5e75f32a88f14fa6aadf7a841056b1ec97e4ab955714d6010495c3bf5e094b2b9eccfd438ba310cb58eb4f087895cca94aa5bd832

test:
  secret_key_base: a033decca8b74cc1864e6863ec165fd96668a7886d7dbe431721519f81db4a517dde417b807a259e55f8b226128b4b9dca85b170341bba57de9d6acc0a280411

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
